# Default values for p1-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enableCertIssuer: true
enableRedis: true

ingress:
  hostname: paysupermgmt.tst.protocol.one
  pathBackend: 
   - /auth1/
   - /conf/
   - /upload_file
   - /order
  pathFrontend: 
   - /

certIssuer:
  email: admin@protocol.one

backend:
  name: nodejs
  role: backend
  image: "paysuper/paysupermanagementsrv-nginx"
  imageTag: latest
  port: 80
  replicas: 1
  service: 
    type: ClusterIP
    port: 80
    protocol: TCP
  env:
  - NODE_ENV
  - AUTH1_CLIENT_ID
  - AUTH1_CLIENT_SCOPE
  - AUTH1_CLIENT_SECRET
  - AUTH1_ISSUER_URL
  - CORS_VALID_ORIGINS
  - HELLOSIGN_CLIENT_ID
  - HELLO_SIGN_TEST_MODE
  - POST_MESSAGE_TARGET_ORIGIN
  - PUBLIC_HOST
  - REDIS_HOST
  - REDIS_PORT
  - ROUTES_PREFIX
  - SENTRY_DSN
  - SERVER_PORT
  - SESSION_COOKIE_NAME
  - SESSION_COOKIE_SIGN_KEY
  - SESSION_MAX_AGE
  - VUE_APP_BACKEND_DOMAIN
  - VUE_APP_P1PAYAPI_URL
  - VUE_APP_WEBSOCKET_URL
  - S3_ACCESS_KEY_ID
  - S3_SECRET_ACCESS_KEY
  - S3_BUCKET_NAME 
  - S3_REGION
  - PAYSUPER_JS_SDK_URL
  - PAYSUPER_PAYMENT_FORM_URL
  - HELLO_SIGN_TEST_MODE
  
frontend:
  name: nginx
  role: frontend
  image: "paysuper/paysupermanagementsrv-nginx"
  imageTag: latest
  port: 80
  replicas: 1
  service: 
    type: ClusterIP
    port: 80
    protocol: TCP
  configMap: 
    mountPath: /etc/nginx/conf.d/
  
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
